### ISSUE TITLE
[ 장바구니 페이지 ] 컨벤션에 따라 리팩토링 하기

### ISSUE THREAD

**Issue by ilmerry** [SOPT-FROZEN/client#13]
# ✅ Todos
- [x] props interface 리팩토링하기
- [x] styled-components아래로 옮기기
- [x] styled-components 선택자 -> 개별요소 모두 선언하기
